### ISSUE TITLE
360 derece videoların hazırlanması

### ISSUE THREAD

**Issue by ybasesme** [Zenciler/Spo-VR#9]
360 derece videoların hazırlanması ile ilgili araştırmalar yapılacak ve uygun yollar izlenerek hareketlerin gösterildiği videolar hazırlanacak.

**Comment by samilkahraman** [comment]
Menü içerikleriyle uyumlu olacak şekilde 360 derece videolar oluşturulup, menü link inşaası tamamlandı.
